<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getSubString</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNClN0cmlu
ZwlpblN0cmluZyA9IElEYXRhVXRpbC5nZXRTdHJpbmcoIHBpcGVsaW5lQ3Vyc29yLCAiaW5TdHJp
bmciICk7DQpTdHJpbmcJYmVnaW5TdHJpbmcgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKCBwaXBlbGlu
ZUN1cnNvciwgImJlZ2luU3RyaW5nIiApOw0KU3RyaW5nCWVuZFN0cmluZyA9IElEYXRhVXRpbC5n
ZXRTdHJpbmcoIHBpcGVsaW5lQ3Vyc29yLCAiZW5kU3RyaW5nIiApOw0KQXJyYXlMaXN0PFN0cmlu
Zz4gYXJybGlzdCA9IG5ldyBBcnJheUxpc3Q8U3RyaW5nPigpOw0KcGlwZWxpbmVDdXJzb3IuZGVz
dHJveSgpOw0KDQppZihpblN0cmluZyE9bnVsbCl7DQoNCglQYXR0ZXJuIHBhdHRlcm4gPSBQYXR0
ZXJuLmNvbXBpbGUoYmVnaW5TdHJpbmcrIiguKj8pIitlbmRTdHJpbmcsIFBhdHRlcm4uRE9UQUxM
KTsNCglNYXRjaGVyIG1hdGNoZXIgPSBwYXR0ZXJuLm1hdGNoZXIoaW5TdHJpbmcpOw0KCQ0KCXdo
aWxlIChtYXRjaGVyLmZpbmQoKSkgew0KCQlhcnJsaXN0LmFkZChtYXRjaGVyLmdyb3VwKDEpKTsN
Cgl9DQoNCglTdHJpbmcgdmFsdWVbXSA9IG5ldyBTdHJpbmdbYXJybGlzdC5zaXplKCldOw0KCU9i
amVjdFtdIG9iakFyciA9IGFycmxpc3QudG9BcnJheSgpOyANCgkgIA0KICAgIC8vIEl0ZXJhdGlu
ZyBhbmQgY29udmVydGluZyB0byBTdHJpbmcgDQogICAgaW50IGkgPSAwOyANCiAgICBmb3IgKE9i
amVjdCBvYmogOiBvYmpBcnIpIHsgDQogICAgCXZhbHVlW2krK10gPSAoU3RyaW5nKW9iajsgDQog
ICAgfSANCiAgICANCiAgICAvLyBwaXBlbGluZQ0KCUlEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29y
XzEgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNCglJRGF0YVV0aWwucHV0KCBwaXBlbGluZUN1cnNv
cl8xLCAidmFsdWUiLCB2YWx1ZSk7DQoJcGlwZWxpbmVDdXJzb3JfMS5kZXN0cm95KCk7DQoJDQp9
</value>
</Values>
