<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getServicePipeline</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgaV9jdXIgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNCnRyeXsNCglJRGF0YVV0
aWwucHV0KGlfY3VyLCAic3ZjUGlwZWxpbmUiLCBJRGF0YVV0aWwuZGVlcENsb25lKHBpcGVsaW5l
KSk7DQp9DQpjYXRjaCAoRXhjZXB0aW9uIGUpIHsNCglJRGF0YSBzdmNQaXBlbGluZSA9IElEYXRh
RmFjdG9yeS5jcmVhdGUoKTsNCglJRGF0YUN1cnNvciBzdmNfY3VyID0gc3ZjUGlwZWxpbmUuZ2V0
Q3Vyc29yKCk7DQoJSURhdGFVdGlsLnB1dChzdmNfY3VyLCAiZmFpbHVyZSIsICJGYWlsZWQgdG8g
Y2FwdHVyZSBwaXBlbGluZSAiK2UuZ2V0TWVzc2FnZSgpKTsNCglJRGF0YVV0aWwucHV0KGlfY3Vy
LCAic3ZjUGlwZWxpbmUiLCBzdmNQaXBlbGluZSk7DQoJc3ZjX2N1ci5kZXN0cm95KCk7DQp9DQpm
aW5hbGx5ew0KCWlfY3VyLmRlc3Ryb3koKTsNCn0=</value>
</Values>
