<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">appendQueryParamsToURL</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgaV9jdXIgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNCklEYXRhIFtdIHBhcmFt
c0FycmF5ID0gSURhdGFVdGlsLmdldElEYXRhQXJyYXkoaV9jdXIsICJwYXJhbXMiKTsNClN0cmlu
ZyB1cmwgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGlfY3VyLCAidXJsIik7DQppZih1cmwuZXF1YWxz
KCIiKSB8fCB1cmwgPT0gbnVsbCkgew0KCXJldHVybjsNCn0NCmVsc2Ugew0KCXVybCA9IHVybC5j
b25jYXQoIj8iKTsNCn0NCmludCBjb3VudCA9IDA7DQpmb3IoSURhdGEgcGFyYW06cGFyYW1zQXJy
YXkpIHsNCglJRGF0YUN1cnNvciBwYXJhbUN1ciA9IHBhcmFtLmdldEN1cnNvcigpOw0KCVN0cmlu
ZyBrZXkgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKHBhcmFtQ3VyLCAia2V5Iik7DQoJaWYoa2V5LmVx
dWFscygiIikgfHwga2V5ID09IG51bGwpIHsNCgkJcmV0dXJuOw0KCX0NCglTdHJpbmcgdmFsdWUg
PSBJRGF0YVV0aWwuZ2V0U3RyaW5nKHBhcmFtQ3VyLCAidmFsdWUiKTsNCgl1cmwgPSB1cmwuY29u
Y2F0KGtleSsiPSIrdmFsdWUpOw0KCWlmKGNvdW50ID09IHBhcmFtc0FycmF5Lmxlbmd0aC0xKXsN
CgkJcGFyYW1DdXIuZGVzdHJveSgpOw0KCX0NCgllbHNlIHsNCgkJdXJsID0gdXJsLmNvbmNhdCgi
JiIpOw0KCQljb3VudD0gY291bnQrMTsNCgl9DQp9DQpJRGF0YVV0aWwucHV0KGlfY3VyLCAidXJs
IiwgdXJsKTsNCmlfY3VyLmRlc3Ryb3koKTs=</value>
</Values>
