<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getFirstDay</value>
  <value name="encodeutf8">true</value>
  <value name="body">TG9jYWxEYXRlIHRvZGF5ID0gTG9jYWxEYXRlLm5vdygpOyANCkxvY2FsRGF0ZSBmaXJzdERheU9m
TW9udGggPSB0b2RheS53aXRoRGF5T2ZNb250aCgxKTsNCg0KTG9jYWxEYXRlIGZpcnN0RGF5T2ZZ
ZWFyID0gdG9kYXkud2l0aChUZW1wb3JhbEFkanVzdGVycy5maXJzdERheU9mWWVhcigpKTsNCkxv
Y2FsRGF0ZSBmaXJzdERheU9mV2VlayA9IHRvZGF5LndpdGgoVGVtcG9yYWxBZGp1c3RlcnMucHJl
dmlvdXNPclNhbWUoRGF5T2ZXZWVrLk1PTkRBWSkpOw0KDQpMb2NhbERhdGUgZmlyc3REYXlPZlF1
YXJ0ZXIgPSB0b2RheS53aXRoKElzb0ZpZWxkcy5EQVlfT0ZfUVVBUlRFUiwgMUwpOw0KDQovLyBw
aXBlbGluZQ0KDQovLyBwaXBlbGluZQ0KSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBl
bGluZS5nZXRDdXJzb3IoKTsNCklEYXRhVXRpbC5wdXQoIHBpcGVsaW5lQ3Vyc29yLCAic3RhcnRZ
ZWFyIiwgZmlyc3REYXlPZlllYXIudG9TdHJpbmcoKSApOw0KSURhdGFVdGlsLnB1dCggcGlwZWxp
bmVDdXJzb3IsICJzdGFydE1vbnRoIiwgZmlyc3REYXlPZk1vbnRoLnRvU3RyaW5nKCkgKTsNCklE
YXRhVXRpbC5wdXQoIHBpcGVsaW5lQ3Vyc29yLCAic3RhcnRXZWVrIiwgZmlyc3REYXlPZldlZWsu
dG9TdHJpbmcoKSApOw0KSURhdGFVdGlsLnB1dCggcGlwZWxpbmVDdXJzb3IsICJzdGFydFF1YXJ0
ZXIiLCBmaXJzdERheU9mUXVhcnRlci50b1N0cmluZygpICk7DQoNCnBpcGVsaW5lQ3Vyc29yLmRl
c3Ryb3koKTsNCgk=</value>
</Values>
