<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">threadedInvoke</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNClN0cmlu
ZwlzdmNOYW1lID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJzdmNOYW1l
IiApOw0KU3RyaW5nCWlmY05hbWUgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKCBwaXBlbGluZUN1cnNv
ciwgImlmY05hbWUiICk7DQppZighcGlwZWxpbmVDdXJzb3IuZmlyc3QoImlmY05hbWUiKSB8fCAh
cGlwZWxpbmVDdXJzb3IuZmlyc3QoInN2Y05hbWUiKSApew0KCQ0KCXRocm93IG5ldyBTZXJ2aWNl
RXhjZXB0aW9uKCJwYWNrYWdlIG9yIHNlcnZpY2UgbmFtZSBjYW5ub3QgYmUgbnVsbCIpOyANCn0N
Cg0KdHJ5ew0KCQ0KCQ0KICAgICAvLyBJbnZva2Ugc2VydmljZQ0KCSANCgkgSURhdGEgc3ZjSW5w
dXQgPSBJRGF0YVV0aWwuZ2V0SURhdGEocGlwZWxpbmVDdXJzb3IsICJwaXBlbGluZSIpOw0KICAg
ICBTZXJ2aWNlLmRvVGhyZWFkSW52b2tlKGlmY05hbWUsIHN2Y05hbWUsIHN2Y0lucHV0KTsNCg0K
ICAgIA0KDQogICB9Y2F0Y2ggKEV4Y2VwdGlvbiBlKXsNCg0KICAgICB0aHJvdyBuZXcgU2Vydmlj
ZUV4Y2VwdGlvbihlLmdldE1lc3NhZ2UoKSk7DQoNCiAgIH1maW5hbGx5ew0KDQoJICAgcGlwZWxp
bmVDdXJzb3IuZGVzdHJveSgpOw0KDQogICB9DQoJ</value>
</Values>
