<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">receiveParallel</value>
  <value name="encodeutf8">true</value>
  <value name="body">ICBJRGF0YUN1cnNvciBpZGNQaXBlbGluZSA9IHBpcGVsaW5lLmdldEN1cnNvcigpOw0KICBTZXJ2
aWNlVGhyZWFkIHN0ID0gbnVsbDsNCg0KICAvL091dHB1dCBWYXJpYWJsZXMgDQogIElEYXRhIG91
dHB1dDsgDQoNCiAgLy8gQ2hlY2sgdG8gc2VlIGlmIHRoZSBydW5uaW5nU2VydmljZSBvYmplY3Qg
aXMgaW4gdGhlIHBpcGVsaW5lDQogIGlmIChpZGNQaXBlbGluZS5maXJzdCgicnVubmluZ1NlcnZp
Y2UiKSkgew0KICAgIC8vZ2V0IHRoZSBmaWxlbmFtZSBvdXQgb2YgdGhlIHBpcGVsaW5lICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgIA0KICAgIHN0ID0gKFNlcnZpY2VUaHJlYWQpIGlk
Y1BpcGVsaW5lLmdldFZhbHVlKCk7DQoNCiAgfQ0KICAvL2lmIGl0IGlzIG5vdCBpbiB0aGUgcGlw
ZWxpbmUsIHRoZW4gaGFuZGxlIHRoZSBlcnJvcg0KDQogIHRyeSB7DQogICAgb3V0cHV0ID0gc3Qu
Z2V0RGF0YSgpOw0KICAgIGlkY1BpcGVsaW5lLmluc2VydEFmdGVyKCJvdXRwdXQiLCBvdXRwdXQp
Ow0KDQogIH0gY2F0Y2ggKEV4Y2VwdGlvbiBlKSB7DQogICAgdGhyb3cgbmV3IElsbGVnYWxBcmd1
bWVudEV4Y2VwdGlvbihlLnRvU3RyaW5nKCkpOw0KICB9</value>
</Values>
