<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">extractDocValues</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGMgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNCklEYXRhIGRvYyA9IElEYXRh
VXRpbC5nZXRJRGF0YShwYywgImRvYyIpOw0KU3RyaW5nIGRlbGltaXRlciA9IElEYXRhVXRpbC5n
ZXRTdHJpbmcocGMsImRlbGltaXRlciIpOw0KU3RyaW5nQnVmZmVyIGJ1ZmZlciA9IG5ldyBTdHJp
bmdCdWZmZXIoKTsNCmlmIChkb2MgIT0gbnVsbCl7DQoJDQoJSURhdGFDdXJzb3IgZGMgPSBkb2Mu
Z2V0Q3Vyc29yKCk7DQoJd2hpbGUgKGRjLm5leHQoKSl7DQoJCQ0KCQlTdHJpbmcgdmFsdWUgPSAo
U3RyaW5nKWRjLmdldFZhbHVlKCk7DQoJCWJ1ZmZlci5hcHBlbmQodmFsdWUpLmFwcGVuZChkZWxp
bWl0ZXIpOw0KCX0NCglkYy5kZXN0cm95KCk7DQp9DQpJRGF0YVV0aWwucHV0KHBjLCAib3V0cHV0
IiwgYnVmZmVyLnRvU3RyaW5nKCkpOw0KCQ0KCXBjLmRlc3Ryb3koKTs=</value>
</Values>
