#Define rolling file appender



#VitalityEngage

log4j.logger.VitalityEngage=TRACE,VitalityEngage
log4j.logger.VitalityEngagePipeline=TRACE,VitalityEngagePipeline
log4j.additivity.VitalityEngage=false
log4j.additivity.VitalityEngagePipeline=false

log4j.appender.VitalityEngage=org.apache.log4j.RollingFileAppender
log4j.appender.VitalityEngage.File=./logs/VitalityEngage.log
log4j.appender.VitalityEngage.Append=true
log4j.appender.VitalityEngage.FileNamePattern=./logs/VitalityEngage.{dd.MM.yyyy}.{X}.log
log4j.appender.VitalityEngage.ImmediateFlush=true
log4j.appender.VitalityEngage.MaxFileSize=1MB
log4j.appender.VitalityEngage.DatePattern='.'yyyy-MM-dd
log4j.appender.VitalityEngage.MaxRollFileCount=10
log4j.appender.VitalityEngage.DateRollEnforced=true
log4j.appender.VitalityEngage.MaxBackupIndex=5
log4j.appender.VitalityEngage.layout=org.apache.log4j.PatternLayout
log4j.appender.VitalityEngage.layout.ConversionPattern=%m%n

log4j.appender.VitalityEngagePipeline=org.apache.log4j.RollingFileAppender
log4j.appender.VitalityEngagePipeline.File=./logs/VitalityEngage_Pipeline.log
log4j.appender.VitalityEngagePipeline.Append=true
log4j.appender.VitalityEngagePipeline.FileNamePattern=./logs/VitalityEngage_Pipeline.{dd.MM.yyyy}.{X}.log
log4j.appender.VitalityEngagePipeline.ImmediateFlush=true
log4j.appender.VitalityEngagePipeline.MaxFileSize=1MB
log4j.appender.VitalityEngagePipeline.DatePattern='.'yyyy-MM-dd
log4j.appender.VitalityEngagePipeline.MaxRollFileCount=10
log4j.appender.VitalityEngagePipeline.DateRollEnforced=true
log4j.appender.VitalityEngagePipeline.MaxBackupIndex=5
log4j.appender.VitalityEngagePipeline.layout=org.apache.log4j.PatternLayout
log4j.appender.VitalityEngagePipeline.layout.ConversionPattern=%m%n