#Define rolling file appender



#VitalityEngage
log4j.rootLogger=TRACE
log4j.logger.VitalityEngage=TRACE,VitalityEngage
log4j.logger.VitalityEngagePipeline=TRACE,VitalityEngagePipeline
log4j.additivity.VitalityEngage=false
log4j.additivity.VitalityEngagePipeline=false

log4j.appender.VitalityEngage=org.apache.log4j.ConsoleAppender
log4j.appender.VitalityEngage.Target=System.out
log4j.appender.VitalityEngage.layout=org.apache.log4j.PatternLayout
log4j.appender.VitalityEngage.layout.ConversionPattern=%m%n

log4j.appender.VitalityEngagePipeline=org.apache.log4j.ConsoleAppender
log4j.appender.VitalityEngagePipeline.Target=System.out
log4j.appender.VitalityEngagePipeline.layout=org.apache.log4j.PatternLayout
log4j.appender.VitalityEngagePipeline.layout.ConversionPattern=%m%n